site_name: GraphBin-Tk
site_url: "https://github.com/Vini2/gbintk"
site_author: "Vijini Mallawaarachchi"
repo_url: "https://github.com/Vini2/gbintk"
repo_name: 'GitHub'
theme:
    name: readthedocs
    highlightjs: true
    hljs_languages:
        - yaml
        - bash
        - shell
        - text
nav:
    - HOME:
      - Introduction: index.md